### ISSUE TITLE
"PaymentProcessor" -- invalid address (arg="_adminAddress", coderType="address", value="")

### ISSUE THREAD

**Issue by sangya2001** [sangya2001/blockchain-ecommerce-app#1]
### Error while deploying contract

Truffle v5.1.41 (core: 5.1.41)
Solidity - 0.6.2 (solc-js)
Node v14.13.1
Web3.js v1.2.1

```
// SPDX-License-Identifier: Non-Licensed
pragma solidity ^0.6.2;
import '@openzeppelin/contracts/token/ERC20/IERC20.sol';

contract PaymentProcessor{
    address public admin;
    IERC20 public dai;

    event PaymentDone(
        address payer,
        uint amount,
        uint paymentId,
        uint date
    );

    constructor(address _adminAddress, address _daiAddress) public{
        admin = _adminAddress;
        dai = IERC20(_daiAddress);
    }

    function pay(uint amount, uint paymentId) external {
        dai.transferFrom(msg.sender, admin, amount);
        emit PaymentDone(msg.sender, amount, paymentId, block.timestamp);
    }
}
```
**Note**: There is no compilation error.

**Comment by oneworldcoder** [comment]
Hello,

I think there needs to be a change in `import`
```
 import "https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/token/ERC20/IERC20.sol";
```

Please let me know if this works.

**Comment by oneworldcoder** [comment]
> This did not solved my issue.

What's the error you are getting?

**Comment by sangya2001** [comment]
> 
> > This did not solved my issue.
> 
> What's the error you are getting?

The same error as the issue title.

**Comment by sangya2001** [comment]
> > The same error as the issue title.
> 
> Are you using Remix? Did you compile the file? On Remix, I can deploy it. 
> 
> ![image](https://user-images.githubusercontent.com/52066039/96214063-28452d80-0f98-11eb-907c-5f99a2674047.png)
> 
> 
> 

Yes it worked on remix but not on local development.

**Comment by oneworldcoder** [comment]
> Yes it worked on remix but not on local development.

Which is the local development?

**Comment by sangya2001** [comment]
> > Yes it worked on remix but not on local development.
> 
> Which is the local development?

I am not using any framework like a truffle but building from scratch.

**Versions**
Truffle v5.1.41 (core: 5.1.41)
Solidity v0.5.16 (solc-js)
Node v14.13.1
Web3.js v1.2.1
